config/routes.rb
Rails.application.routes.draw do

  match '/signin', to: 'sessions#new', via: 'get'
  match '/signout', to: 'sessions#destroy', via: "delete"

  resources :sessions, only: [:new, :create, :destroy]
  resources :posts, only: [:new, :create, :destroy]
  resources :users
  root 'posts#index'
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :user
end

app/models/user.rb
class User < ActiveRecord::Base
  before_create :create_remember_token

  validates :name, presence: true, length: { maximum: 50 }
  validates :email, presence: true
  validates :password, length: { minimum: 6 } 

  has_many :posts
  has_secure_password

  def User.new_remember_token
    SecureRandom.urlsafe_base64
  end

  def User.digest(token)
    Digest::SHA1.hexdigest(token.to_s)
  end

  private

    def create_remember_token
      self.remember_token = User.digest(User.new_remember_token)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  # only signed in user can access the #new and #create action
  before_action :signed_in_user, only: [:new, :create]

  def index
    @posts = Post.all
  end

  def new
  	@post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.user_id = current_user.id

    @post.save
    redirect_to root_path
  end

  def destroy
    @post = Post.find(params[:id])
    @post.destroy

    redirect_to(:back)
    flash[:error] = "Post has been deleted"
  end

  private

    def signed_in_user
  	  redirect_to signin_path, notice: "Please sign in" unless signed_in?
    end

    def post_params
      params.require(:post).permit(:title, :body)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end

  def create

    # Using the form sessions/new.html.erb -> params hash is constructed, 
    # containing email and password under the session key. Retrieve by: 
  	user = User.find_by(email: params[:session][:email].downcase)

    # if user is in database and user typed in correct password: 
  	if user && user.authenticate(params[:session][:password])
      flash[:success] = "Thank you for signing in" 
      #uses sign_in method in sessions_helper.rb (included in ApplicationController)
  	  sign_in user     
      redirect_to root_path
  	else    
      flash.now[:error] = "Wrong email or password"                                             
  	  render "new"
  	end
  end

  def destroy
    #uses sign_out method in sessions_helper.rb (included in ApplicationController)
    flash[:success] = "You have been signed out"
    sign_out
    redirect_to root_path
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def index
  	@users = User.all
  end

  def show
  	@user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def sign_in(user) 
  	# create a new token
    remember_token = User.new_remember_token	

    # save the new token in a browser's cookie
    cookies.permanent[:remember_token] = remember_token 

    # update database with new token (update_attribute -> can surpass the validation
    # since we don't have user's password or confirmation here!)
    user.update_attribute(:remember_token, User.digest(remember_token)) 	
    self.current_user = user
  end

  # in order to retrieve the current user (e.g. put it in controller or view)
  # we need to create a "set current_user" method

  def current_user=(user)
  	@current_user = user
  end						

  def current_user
  	remember_token = User.digest(cookies[:remember_token])
  	@current_user ||= User.find_by(remember_token: remember_token)
  end

  # a user is signed in if there is a current user in the session (if current_user is not nil)
  def signed_in?
  	!current_user.nil?
  end

  def sign_out
  	# change the user's remember token in the database (in case it could be stolen)
  	current_user.update_attribute(:remember_token, User.digest(User.new_remember_token))
  	cookies.delete(:remember_token)
  	self.current_user = nil
  end
end

app/views/layouts/_header.html.erb
<header>
  <div class="container">
    <div id="Logo"><%= link_to "Lästerschwester", root_path %></div>
    <nav>
	  <ul class="nav pull-right">
	    <li><%= link_to "Home", root_path %></li>
	    <% if signed_in? %>
	      <li><%= link_to "New Post", new_post_path %></li>
	      <li><%= link_to "Profile", current_user %></li>
	      <li><%= link_to "Log out", signout_path, method: "delete" %></li>
	    <% else %>
	      <li><%= link_to "Login", signin_path %></li>
	    <% end %>
	  </ul>
    </nav>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>MembersOnly</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link href='http://fonts.googleapis.com/css?family=Karla|Lobster' rel='stylesheet' type='text/css'>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  <%= render "layouts/header" %>

<%= yield %>

</body>
</html>

app/views/posts/index.html.erb
<div class="container">

  <% flash.each do |key, value| %>
    <%= content_tag :div, value, class: "flash #{key}" %>
  <% end %> 

  <% @posts.order("created_at desc").each do |post| %>
  <div class="post">
    <h1><%= post.title %></h1>
    <p><%= post.body %></p>

    <% if signed_in? %>
      <p>Created by: <%= post.user.name %></p>

    <% end %>
  </div>
  <% end %>
</div>

app/views/posts/new.html.erb
<div class="container">
  <h1>Create a new post</h1>

  <%= form_for(@post) do |f| %>
  
    <p><%= f.label :title %></p>
    <p><%= f.text_field :title %></p>

    <p><%= f.label :body %></p>
    <p><%= f.text_area :body %></p>

    <p><%= f.submit "Submit" %></p>

  <% end %>
</div>

app/views/users/index.html.erb
<h1>All users</h1>
   <% flash.each do |key, value| %>
     <%= value %>
   <% end %> 
<ul>
  <% @users.each do |user| %>
    <li> <%= user.name %> | <%= user.email %> </li>
  <% end %>
</ul>

<%= link_to "Sign in", signin_path %>

app/views/users/show.html.erb
<div class="container">
  <ul>
    <li> <%= @user.name %> | <%= @user.email %> </li>
  </ul>
</div>